const data = {
  products: [
    {
      name: "Nike Shirt",
      slug: "nike-shirt",
      category: "Shirts",
      image: "/images/p1.jpg", // 679px x 829px
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Adidas Shirt",
      slug: "adidas-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 75,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Puma Shirt",
      slug: "puma-shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 95,
      countInStock: 15,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Shirt",
    },
    {
      name: "Nike Pants",
      slug: "nike-pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Pants",
    },
    {
      name: "Adidas Pants",
      slug: "adidas-pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 100,
      countInStock: 5,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Pants",
    },
  ],
};

export default data;
